Update to Rust 2018
cjhowe7/named_type pull request #8
Opened 2019-02-07 14:38 UTC by thomaslienbacher

Changes:
* Updated code
* Updated examples in the documentation
* Added my name to the Cargo.toml files

I didn't update the version number, because I don't know if this would equal a major or a minor update.
Addresses this issue: #7 

This is my first pull request, so please give me some hints on how to make them better.

2019-02-09 02:24 UTC, cjhowe7 commented
I left some review comments. I think this is going to be a patch update because it's mostly documentation changes. [Technically it doesn't matter](https://semver.org/#spec-item-4) according to semver for versions less than 1.0 though. Thanks for contributing!

2019-02-09 02:25 UTC, cjhowe-us requested changes

2019-02-09 02:25 UTC, cjhowe7 commented on .gitignore
> +.idea
```suggestion
```
I used to do this too, before I learned about setting up a [global `.gitignore`](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore) for these kinds of rules. I don't think this change is necessary.

2019-02-09 02:25 UTC, cjhowe7 commented on named_type_derive/src/lib.rs
> +use quote::*;
```suggestion
use quote::{Tokens, quote};
```

I'd prefer to explicitly import only what we use in the namespace. Note that there's a `quote::Tokens` line in this file which would no longer need the prefix.

2019-02-09 12:13 UTC, thomaslienbacher commented
I have applied your suggestions and updated the version number, by incrementing the patch number.
I think this branch is ready to be squashed and merged.

2019-02-12 06:36 UTC, cjhowe-us approved these changes

2019-02-12 06:36 UTC, cjhowe7 commented
Merged. Thank you!

2019-02-12 06:36 UTC, closed without merging